baseURL: "https://example.com"
languageCode: "en-us"
title: "Hugo Novela"
pygmentsstyle: "monokai"
paginate: 6
params:
  social:
    twitter: "#"
    github: "#"
    instagram: "#"
    linkedin: "#"
    dribbble: "#"
    youtube: "#"
taxonomies:
  author: authors
